### PR TITLE
feat: Make sx_multi a Python library

### PR DESCRIPTION
**Pull request by matthewfeickert**
Make `sx_multi` a Python 3 library that can be installed in editable mode for development along with all of its dependencies with

```
python -m pip install -e .[complete]
```

**Suggested squash and merge commit message:**

```
* Use src directory structure for Python library
   - Add MIT License
   - Use setup.cfg for metadata, options, and required libraries
   - Use setup.py for logic operations required for various extras
* Add pre-commit config file for flake8 and pyupgrade
   - Make necessary changes to pass flake8
* Add simple CI to test installation with GitHub Actions
* Remove amending of sys.path for notebooks
   - sx_multi will be installed and findable
```

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@gordonwatts I've rebased this against your `main` branch and I have it passing CI on my fork: https://github.com/matthewfeickert/servicex-coffea-multiprocessing/actions so this should be ready for review. Let me know if you have any questions or requested changes.

**Comment by gordonwatts** [comment]
Wow - that must have been a lot of work! Thanks so much!!

**Comment by matthewfeickert** [comment]
> Wow - that must have been a lot of work! Thanks so much!!

:) It actually was _very_ easy given that you already had everything in modules &mdash; so thanks for making it so. I have gotten quite a bit of experience with turning small projects into libraries in the last year, and I've already promised @kratsg that I would make my https://github.com/matthewfeickert/Python-library-template a Cookiecutter project template so that this is even easier in the future.

Let me know if you have any questions about things in the future and thanks also for putting all of this together in the first place!

**Comment by gordonwatts** [comment]
Thanks, I will. the `cfg` file looks more complex than the `setup.py` file used to. Sigh. And the extras thing is missing!!

I tagged what is at the head as 0.1.0 - because this week we will start trying to automate some of the boilerplate, and that will very much break the way current scripts are running.

**Comment by matthewfeickert** [comment]
> Thanks, I will. the `cfg` file looks more complex than the `setup.py` file used to. Sigh. And the extras thing is missing!!

@gordonwatts What's the "extras" thing? If you mean the `setup.py` extras those still exist, but I put them in `setup.py` instead of `setup.cfg` as they require logic:

https://github.com/gordonwatts/servicex-coffea-multiprocessing/blob/73c6eecb39bffc9cba4e4cf30f506d683cccf900/setup.py#L3-L9

The idea of `setup.cfg` (as the PyPA puts it) is to move everything that doesn't require logic into a static file. `setup.py` is just a Python script and so the idea there is "only encode in it what requires logic and leave the metadata and the rest to `setup.cfg`".

**Comment by gordonwatts** [comment]
Yeah - that was the extras thing - ok - thanks. Any chance this setup.cfg will stick? Should I start moving things over? Or wait till it "stabilizes" a bit? :-)

**Comment by matthewfeickert** [comment]
> Any chance this setup.cfg will stick?

"Stick" as in be a common thing recommended by the PyPA? If so, then yes, as [it has been for a few years now](https://github.com/pypa/sampleproject). What is of varying level of support right now is `pyproject.toml`. Brett Cannon (Python Steering Council) has a good series of posts on this &mdash; I'd recommend maybe starting with "[What the heck is pyproject.toml?](https://snarky.ca/what-the-heck-is-pyproject-toml/)".

**Pull request merged**
